# Netflix User Analytics Assignment

**Name: Akshiti Singh**
<br>
**Enrollment Number:01001182025**
<br>
**College:IGDTUW**
<br>
**Branch:ECE-AI**

In [26]:
import pandas as pd

df = pd.read_excel("Dataset 2.xlsx")

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [27]:
#Determining the number of rows and columns
df.shape

(750, 10)

In [28]:
#Displaying all the columns names

df.columns

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [29]:
#Identifying numerical and categorical features

print("Numerical Columns:")
print(df.select_dtypes(include=['int64','float64']).columns)

print("\nCategorical Columns:")
print(df.select_dtypes(include=['object']).columns)

Numerical Columns:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Columns:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [30]:
#Checking whether the dataset contains missing values
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [31]:
#Calculate the average age of users

df["Age"].mean()

np.float64(41.824)

In [32]:
# Determine the average watch hours per week

df["WatchHoursPerWeek"].mean()

np.float64(14.236)

In [33]:
#Find the average monthly spending of users

df["MonthlySpend"].mean()

np.float64(689.9053333333334)

In [34]:
#Count the number of users in each subscription category

df["SubscriptionType"].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [35]:
#Determine the percentage of users who renewed their subscription

(df["SubscriptionRenewed"] == "Yes").mean() * 100

np.float64(46.266666666666666)

In [36]:
#Convert categorical features into numerical form

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["SubscriptionType"] = le.fit_transform(df["SubscriptionType"])
df["FavoriteGenre"] = le.fit_transform(df["FavoriteGenre"])
df["SubscriptionRenewed"] = le.fit_transform(df["SubscriptionRenewed"])

df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [37]:
#Define the feature set (X) and target variable (y)

X = df.drop(["UserID", "SubscriptionRenewed"], axis=1)

y = df["SubscriptionRenewed"]

print(X.head())
print(y.head())

   Age  Gender  SubscriptionType  WatchHoursPerWeek  DevicesUsed  \
0   22       0                 0                 23            5
1   55       1                 0                  9            4
2   49       1                 0                  8            3
3   39       0                 1                 19            5
4   38       0                 1                 23            5

   FavoriteGenre  AdClicks  MonthlySpend
0              1        13           353
1              2        14           317
2              1        16           309
3              2        45           833
4              5        24           804
0    0
1    1
2    0
3    1
4    1
Name: SubscriptionRenewed, dtype: int64

In [38]:
#Split the dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (600, 8)
Testing data: (150, 8)

In [39]:
#Train a Decision Tree model

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [40]:
#Evaluate the model using accuracy
from sklearn.metrics import accuracy_score

y_pred = dt.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.56

In [41]:
#Generate and interpret the confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[48 34]
 [32 36]]

In [42]:
#Train a KKN classifier With K=5

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

In [43]:
#Compare the accuracy of KNN with the Decision Tree model

from sklearn.metrics import accuracy_score

knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("Decision Tree Accuracy:", accuracy)
print("KNN Accuracy:", knn_accuracy)

Decision Tree Accuracy: 0.56
KNN Accuracy: 0.6333333333333333

In [44]:
#Linear Regression

from sklearn.linear_model import LinearRegression

X_reg = df.drop(["UserID", "MonthlySpend"], axis=1)

y_reg = df["MonthlySpend"]

from sklearn.model_selection import train_test_split

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

lr = LinearRegression()

lr.fit(X_train_reg, y_train_reg)

LinearRegression()

In [46]:
new_user = [[25, 1, 2, 15, 3, 1, 5, 1]]

predicted_spend = lr.predict(new_user)

print("Predicted Monthly Spend:", predicted_spend[0])

Predicted Monthly Spend: 1316.5425890917948

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### 1. Which factors appear to influence subscription renewal the most?
Watch hours per week, subscription type, monthly spending, devices used, and favorite genre appear to have the greatest influence on whether a user renews their subscription.

## 2. Why is subscription renewal a classification problem?
Subscription renewal is a classification problem because the target variable has two possible categories: Yes or No.

## 3. Why is monthly spending a regression problem?
Monthly spending is a regression problem because it is a continuous numerical value that can take many different amounts.

## 4. Which algorithm performed better for renewal prediction?
KNN performed better because its accuracy was higher than the Decision Tree model.

## 5. How could the platform use these predictions to improve customer retention?
Netflix can identify users who are likely not to renew their subscriptions and offer personalized recommendations, discounts, or special offers to encourage them to stay subscribed.

# Conclusion

*The Netflix user dataset was analyzed using Machine Learning techniques. Decision Tree, KNN, and Linear Regression models were applied. KNN achieved higher accuracy for subscription renewal prediction, while Linear Regression was used to estimate monthly spending.:*